name: .NET CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./CV-Checker-Backend/CV-Checker-Backend.slnx

      - name: Build solution
        run: dotnet build ./CV-Checker-Backend/CV-Checker-Backend.slnx --configuration Release --no-restore

      - name: Publish API
       run: dotnet publish .\CVApi\CVApi.csproj --configuration Release --output ./publish --no-build

      - name: Upload published API artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ./publish
